lib: do not export non-existent `hasFile`
`hasFile` does not exist at least in `nix-2.32`. I
suspect it was a typo of a nearby `hashFile`.

Noticed as an eval failure:

    nix-repl> lib.hasFile
    error:
       … while evaluating the attribute 'hasFile'
         at lib/default.nix:113:9:
          112|         hashString
          113|         hasFile
             |         ^
          114|         parseDrvName

       error: attribute 'hasFile' missing
       at lib/default.nix:113:9:
          112|         hashString
          113|         hasFile
             |         ^
          114|         parseDrvName
       Did you mean hashFile?